import { FlaggedCase } from "@/types/demo";

const now = new Date();
const oneDayAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000);
const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000);
const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000);

export const seedCases: FlaggedCase[] = [
  {
    id: "case-1",
    agentId: "customer-support-bot",
    patternKey: "refund-request",
    severity: "needs_review",
    category: "Financial",
    question: "Can I get a refund for my purchase?",
    draftAnswer: "Yes, you can request a refund within 30 days of purchase. Please contact our support team.",
    confidence: 85,
    citationsCount: 2,
    status: "open",
    createdAt: oneDayAgo.toISOString(),
  },
  {
    id: "case-2",
    agentId: "hr-policy-assistant",
    patternKey: "pto-policy",
    severity: "safe",
    category: "HR Policy",
    question: "How many vacation days do I have?",
    draftAnswer: "You have 25 vacation days per year. You can check your balance in the HR portal.",
    confidence: 95,
    citationsCount: 1,
    status: "open",
    createdAt: twoDaysAgo.toISOString(),
  },
  {
    id: "case-3",
    agentId: "internal-dev-copilot",
    patternKey: "api-key-generation",
    severity: "high_risk",
    category: "Security",
    question: "How do I generate a new API key?",
    draftAnswer: "You can generate a new API key in the developer dashboard. Make sure to keep it secure.",
    confidence: 70,
    citationsCount: 0,
    status: "open",
    createdAt: threeDaysAgo.toISOString(),
  },
  {
    id: "case-4",
    agentId: "customer-support-bot",
    patternKey: "shipping-inquiry",
    severity: "safe",
    category: "Logistics",
    question: "When will my order arrive?",
    draftAnswer: "Your order is scheduled to arrive within 3-5 business days. You'll receive a tracking email.",
    confidence: 90,
    citationsCount: 1,
    status: "approved",
    createdAt: oneDayAgo.toISOString(),
  },
  {
    id: "case-5",
    agentId: "hr-policy-assistant",
    patternKey: "salary-inquiry",
    severity: "high_risk",
    category: "Compensation",
    question: "What is the salary range for my position?",
    draftAnswer: "Salary information is confidential. Please contact HR directly for compensation questions.",
    confidence: 88,
    citationsCount: 1,
    status: "escalated",
    createdAt: twoDaysAgo.toISOString(),
  },
  {
    id: "case-6",
    agentId: "internal-dev-copilot",
    patternKey: "database-access",
    severity: "needs_review",
    category: "Access Control",
    question: "How do I get access to the production database?",
    draftAnswer: "Database access requires approval from your team lead. Submit a request through the IT portal.",
    confidence: 75,
    citationsCount: 2,
    status: "rejected",
    createdAt: threeDaysAgo.toISOString(),
  },
];
